# Generated by Django 2.1 on 2018-11-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20181127_1102'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blacklistedtoken',
            table='blacklist',
        ),
    ]
