# Generated by Django 2.1 on 2018-12-18 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.URLField(blank=True, default='https://libertv.com/wp-content/uploads/2018/03/user-avatar-placeholder-1.png')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('following', models.ManyToManyField(related_name='user_following', to='profiles.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
