# Generated by Django 2.1 on 2018-12-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181218_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='highlight_end',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='comment',
            name='highlight_start',
            field=models.IntegerField(default=0),
        ),
    ]
